### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by YuQuankun** [stylepatrick/trading-price-prediction#2]
hello, i want to know that in main.py, what's the x_train ,y_train mean? I think the x_train should be the time, and the y_train should be the data, but it seems that in your code ,the x_train is not the time?

**Comment by stylepatrick** [comment]
Hello, no the x_train and y_train both includes price values from the scaled_data. The y_train is used to add the 61 value, if the prediction days is set to 60 days. You will fit the model with the x_train and y_train where the real "CLOSE" values are stored. The Neural Network is then learning the rule to come to the y_train result on the basis from x_train. The rule is then used to predict prices.

**Comment by YuQuankun** [comment]
thanks for your answer, but plz forgive that i still can't understand your meaning. Could you explain it more specifically ? for example, how the prices values become x_train and y_train?

**Comment by YuQuankun** [comment]
thanks, i have understood what the code meaning.
